### ISSUE TITLE
Implementamos esse modulo, mas temos erros

### ISSUE THREAD

**Issue by cristiano-acosta** [vanderson139/opencart-cielo#1]
<b>Notice</b>: Trying to get property of non-object in <b>/home/mundobra/public_html/catalog/controller
/payment/cielo.php</b> on line <b>410</b>
#0 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo

/Requisicao.php(255): SimpleXMLElement->__construct('')
#1 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(402): Tritoq\Payment\Cielo\Requisicao->send('/home2/mundobra...')
#2 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(477): Tritoq\Payment\Cielo\CieloService->enviaRequisicao(Object(SimpleXMLElement))
#3 /home/mundobra/public_html/catalog/controller/payment/cielo.php(343):

Tritoq\Payment\Cielo\CieloService->doTransacao(false, false)
#4 [internal function]:

ControllerPaymentCielo->processar(Array)
#5 /home/mundobra/public_html/vqmod/vqcache/vq2-system_engine_action.php(65): call_user_func(Array, Array

)
#6 /home/mundobra/public_html/system/engine/front.php(34): Action->execute(Object(Registry))
#7 /home/mundobra/public_html/system/engine/front.php(29): Front->execute(Object(Action))
#8 /home/mundobra/public_html/index.php(260): Front->dispatch(Object(Action), Object(Action))
#9 {main}<b>Notice</b>: Trying to get property of non-object in <b>/home/mundobra/public_html/catalog

/controller/payment/cielo.php</b> on line <b>410</b>ERRO: Retorno vazio, verifique o caminho e a vers&atilde;o do certificado SSL!{"error":["",""]}

**Comment by vanderson139** [comment]
Esse Notice foi corrigido na versão 1.1.8.

Você seguiu as recomendações para contornar o erro com o certificado SSL? Está na descrição do módulo.

**Comment by cristiano-acosta** [comment]
ainda não temos uma solução, aplicamos esse detalhe do SSL e não funcionou.
Tomei a liberdade de corrigir na linha 410 do controller/payment/cielo.php:
//$this->error[] = utf8_decode((string)$error->mensagem);
$this->error[] = utf8_decode($error["mensagem"]);

mas os erros ainda persistem:
#0 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/Requisicao.php(255):SimpleXMLElement->__construct('')
Pelo que entendi aqui ele não esta construindo um xml necessario??

#1 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(402): Tritoq\Payment\Cielo\Requisicao->send('/home2/mundobra...')
Aqui ele esta enviando para a cielo o arquivo, mas não consigo ver qual seria

#2 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(477): Tritoq\Payment\Cielo\CieloService->enviaRequisicao(Object(SimpleXMLElement))
Aqui esta enviando como objeto, mas não o que deveria enviar...

#3 /home/mundobra/public_html/catalog/controller/payment/cielo.php(343): Tritoq\Payment\Cielo\CieloService->doTransacao(false, false)
Não executa a transação provavelmente por que não envia os parametros corretos para a Cielo

#4 [internal function]: ControllerPaymentCielo->processar(Array)

#5 /home/mundobra/public_html/vqmod/vqcache/vq2-system_engine_action.php(65): call_user_func(Array, Array)
#6 /home/mundobra/public_html/system/engine/front.php(34): Action->execute(Object(Registry))

#7 /home/mundobra/public_html/system/engine/front.php(29): Front->execute(Object(Action))

#8 /home/mundobra/public_html/index.php(260): Front->dispatch(Object(Action), Object(Action))

#9 {main}ERRO: Retorno vazio, verifique o caminho e a vers&atilde;o do certificado SSL!{"error":["#"
,"E"]}

Seria o caso de alterar a versão do SSL para a compativel com o a do servidor? Poderia auxiliar nisso?
Link da loja: https://mundobranco.com.br/

**Comment by vanderson139** [comment]
Essa biblioteca não deveria estar nessa pasta "public_html/vqmod/vqcache/Tritoq", mas sim em "public_html/system/library/Tritoq". É possível que não esteja conseguindo encontrar o caminho do certificado por causa disso. 

Vocês estão usando um template customizado, tipo Journal2 ou similar?

**Comment by cristiano-acosta** [comment]
vqmod e o template moda

**Comment by cristiano-acosta** [comment]
mas não acredito que seja somente esse detalhe, seria??
como ele processa o certificado?? não seria apenas remodelar os caminhos... 

como tem vqmod instalado no sistema ele reescreve o  cielo.php e nisso acaba perdendo os caminhos corretos, por isso que inserimos a pasta Tritoq dentro do vqcache...

alguma incompatibilidade entre o ocmod e o vqmod nesse caso??

**Comment by vanderson139** [comment]
o caminho para o certificado é absoluto:

DIR_SYSTEM . 'library/Tritoq/Payment/Cielo/ssl/ecommerce.cielo.com.br.cer

Talvez você precise alterar.

**Comment by cristiano-acosta** [comment]
Quando utilizamos o nosso certificado, ele pode ser na extensão .crt?

**Comment by vanderson139** [comment]
Não, acho que você entendeu errado. Não pode ser o certificado de vocês.

Esse certificado tem que ser o da Cielo, para que o CURL valide a conexão com o servidor deles de forma segura.

**Comment by mathidios** [comment]
Olá, @vanderson139, realizei a instalação e a compra NÃO em modo teste pela cielo de um produto de R$1,00 que foi cobrado em meu cartão e retorna essa mensagem:

Falha no pagamento!
Houve um problema ao processar o seu pagamento, por isso, seu pedido não foi concluído.
Possíveis causas:
•Não a crédito suficiente.
•Falha na verificação.
Você pode tentar novamente utilizando outra forma de pagamento.
Se o problema persistir, entre em contato conosco e nos informe os detalhes do seu pedido.

O que posso fazer?

**Comment by vanderson139** [comment]
Olá, @mathidios, o valor foi debitado do seu cartão? Verifique as mensagens da transação na tabela 'oc_order_cielo'

**Comment by cristiano-acosta** [comment]
ainda estamos enfrentando dificuldades neste modulo, poderia me add no skype ou facebook para falarmos mais pessoalmente??

**Comment by mathidios** [comment]
@vanderson139 a "autorizacao_mensagem" no BD esta como "Transacaoo autorizada". No extrato do cartão de credito apresenta a cobrança. O único problema é esta mensagem no final falando de falha.

**Comment by cristiano-acosta** [comment]
Cara so falta isso para terminar esse projeto, por favor me ajude cara!!!

ERRO: Retorno vazio, verifique o caminho e a versão do certificado SSL!

#0 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/Requisicao.php(321): SimpleXMLElement->__construct('') #1 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(495): Tritoq\Payment\Cielo\Requisicao->send('/home2/mundobra...') #2 /home/mundobra/public_html/vqmod/vqcache/Tritoq/Payment/Cielo/CieloService.php(604): Tritoq\Payment\Cielo\CieloService->enviaRequisicao(Object(SimpleXMLElement)) #3 /home/mundobra/public_html/catalog/controller/payment/cielo.php(335): Tritoq\Payment\Cielo\CieloService->doTransacao(false, false) #4 [internal function]: ControllerPaymentCielo->processar(Array) #5 /home/mundobra/public_html/vqmod/vqcache/vq2-system_engine_action.php(65): call_user_func(Array, Array) #6 /home/mundobra/public_html/system/engine/front.php(34): Action->execute(Object(Registry)) #7 /home/mundobra/public_html/system/engine/front.php(29): Front->execute(Object(Action)) #8 /home/mundobra/public_html/index.php(260): Front->dispatch(Object(Action), Object(Action)) #9 {main}

Ainda esta dando erro

**Comment by mathidios** [comment]
@cristiano-acosta ja tentou realizar o procedimento abaixo?

No arquivo system/library/Tritoq/Payment/Cielo/Requisicao.php altere o parâmetro CURLOPT_SSL_VERIFYPEER para false na linha 287

**Comment by cristiano-acosta** [comment]
Sim, já alterei. Pelo o que percebo não está gerando o XML. Não consigo solucionar o problema...

**Comment by mathidios** [comment]
O modulo esta em modo teste?
Ja ocorreu a homologação da cielo?
Preencheu as informações solicitadas no admin do modulo?

**Comment by cristiano-acosta** [comment]
O modulo esta em modo teste?
Sim!
Ja ocorreu a homologação da cielo?
Não!
Preencheu as informações solicitadas no admin do modulo?
Sim!!!

**Comment by mathidios** [comment]
Para mim, estava apresentando o memso problema. Após alterar a linha 287, a cielo homologar funcionou perfeitamente.

**Comment by vanderson139** [comment]
@cristiano-acosta outros usuários estão enfrentando problemas de incompatibilidade com o vqmod. Não consegui solucionar isso ainda. Se você puder não utilizar o vqmod acredito que irá funcionar.

**Comment by cristiano-acosta** [comment]
posso ajudar em algo??

**Comment by vanderson139** [comment]
@cristiano-acosta pode sim, toda ajuda é bem-vinda. Se conseguir solucionar o problema, mande um pull request.

**Comment by cristiano-acosta** [comment]
cara esse modulo tambem trabalha com checkout?

**Comment by vanderson139** [comment]
por enquanto não

**Comment by sistemaweb** [comment]
fala Vanderson, blz? mano, estou usando seu módulo Cielo e queria saber quanto você cobra pra corrigir o erro da incompatibilidade com o vqmod, eu sei q vc vai corrigir em breve, mas precisaria o mais rápido possível, quanto c cobra pra corrigir?

meu e-mail: sistemaweb.info@gmail.com

**Comment by vanderson139** [comment]
@sistemaweb obrigado, mas já estou trabalhando nisso. O problema é que estou com pouco tempo disponível no momento.
