### ISSUE TITLE
Opencart 2.1

### ISSUE THREAD

**Issue by criarth** [vanderson139/opencart-cielo#10]
Olá Vanderson,

1º quero lhe parabenizar pelo excelente módulo! Estou utilizando seu módulo Cielo no Opencart 2.0.3.1, mas estou com o projeto de criar uma outra loja com a nova versão 2.1.0.1. Sabe me informar se o a versão atual de seu módulo funciona com a nova versão o Opencart?

**Comment by vanderson139** [comment]
Olá amigo! Obrigado.

Não testei nessa versão, então não sei te dizer. Mas, pelo que eu li no changelog, deve-se atentar para a função de carregamento do arquivo de linguagem. Alterando essas linhas o módulo deve funcionar.

$this->load->language alterar para  $this->language->load

**Comment by criarth** [comment]
Obrigado por responder, vou fazer a alteração, testar e posto aqui se deu certo ou não.
