### ISSUE TITLE
ERRO: Retorno vazio, verifique o caminho e a versão do certificado SSL!

### ISSUE THREAD

**Issue by lguilhermecardoso** [vanderson139/opencart-cielo#11]
Bom dia estou com esse erro aqui não consigo resolver-lo. Retorna isso pra mim

ERRO: Retorno vazio, verifique o caminho e a versão do certificado SSL!
#0 /home/shopdcor/public_html/system/library/Tritoq/Payment/Cielo/Requisicao.php(320): SimpleXMLElement->__construct('') #1 /home/shopdcor/public_html/system/library/Tritoq/Payment/Cielo/CieloService.php(495): Tritoq\Payment\Cielo\Requisicao->send('/home/shopdcor/...') #2 /home/shopdcor/public_html/system/library/Tritoq/Payment/Cielo/CieloService.php(604): Tritoq\Payment\Cielo\CieloService->enviaRequisicao(Object(SimpleXMLElement)) #3 /home/shopdcor/public_html/catalog/controller/payment/cielo.php(344): Tritoq\Payment\Cielo\CieloService->doTransacao(false, false) #4 [internal function]: ControllerPaymentCielo->processar(Array) #5 /home/shopdcor/public_html/system/modification/system/engine/action.php(65): call_user_func(Array, Array) #6 /home/shopdcor/public_html/system/engine/front.php(34): Action->execute(Object(Registry)) #7 /home/shopdcor/public_html/system/engine/front.php(29): Front->execute(Object(Action)) #8 /home/shopdcor/public_html/index.php(256): Front->dispatch(Object(Action), Object(Action)) #9 {main}

**Comment by lguilhermecardoso** [comment]
algum pode me ajudar?

**Comment by caniss** [comment]
Na descrição do módulo na loja da opencart, tem uma instrução, já tentou ela?

http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22214&path=3&filter_search=cielo&filter_license=0

No arquivo system/library/Tritoq/Payment/Cielo/Requisicao.php altere o parâmetro CURLOPT_SSL_VERIFYPEER para false na linha 287

**Comment by lguilhermecardoso** [comment]
Ja alterei sim caniss :/ porem continua acusando esses erros
