### ISSUE TITLE
Nada acontece (Opencart 2.1.0.1)

### ISSUE THREAD

**Issue by Gataquadrada** [vanderson139/opencart-cielo#12]
Olá, tudo bem?
Então, eu instalei o módulo e configurei de acordo com as credenciais de desenvolvedor da CIELO (https://developercielo.github.io/Webservice-1.5/).

Mas quando informo os dados do cartão no checkout e clico em "Efetuar Pagamento" (http://i.imgur.com/95HYl25.png), nada acontece. Nem mensagem de erro.

Teria alguma ideia do que poderia ser?

Ah, o log de erros do OC está vazio, também...

**Comment by lguilhermecardoso** [comment]
Tenta abrir o inspecionador de elementos e verifique o console pra ver se ele esta dando algum erro de javascript. algo assim

**Comment by Gataquadrada** [comment]
Já tinha pensado nisso. 
O console está limpo...

O formulário chega a bloquear o botão de submit e ficar "Carregando...". Mas, um segundo depois, ele desbloqueia e nada acontece.

**Comment by adilsonmenezes** [comment]
O nome dá loja contém acentos/cedilha? Eu tive este problema, e retirei o nome da loja com esta caracteristica, pois no xml que estava sendo gerado, continha ? nos caracteres acentuados. Outra coisa é incluir o comando de str_replace na linha:

} else if(!isset($this->_valida_cartao[$this->request->post['creditcard_cctype']]) || !preg_match($this->_valida_cartao[$this->request->post['creditcard_cctype']]['regexp'], $this->request->post['creditcard_ccno'])) {

ficando: 

} else if(!isset($this->_valida_cartao[$this->request->post['creditcard_cctype']]) || !preg_match($this->_valida_cartao[$this->request->post['creditcard_cctype']]['regexp'], str_replace(' ', '',$this->request->post['creditcard_ccno']))) {

**Comment by Gataquadrada** [comment]
O nome da loja nem espaços tem. Muito menos acentos.
Fiz a alteração, mas... Mesma coisa.
De qualquer forma, obrigado pela atenção.

**Comment by vanderson139** [comment]
@FineRapha vou subir uma correção pra isso, por enquanto basta alterar a forma de parcelamento para 'Loja' ao invés de 'Administradora' na configuração do módulo

**Comment by Gataquadrada** [comment]
@vanderson139 
Já havia feito isso.
O resultado continua o mesmo:
1) O botão fica desabilitado ("Carregando...").
2) Nada acontece e nada é mostrado no console.
3) O botão é reabilitado.

Seja a configuração estando "Parcelamento Loja" ou "Administradora".

Estou usando o modo de testes, também.

**Comment by vanderson139** [comment]
veja o retorno no arquivo de log 'system/storage/logs/cielo.log'

**Comment by Gataquadrada** [comment]
Esse arquivo não existe...

**Comment by vanderson139** [comment]
o display errors do php e da loja estão ativados? se estiver, veja a mensagem que aparece no console ou no log do seu php

**Comment by Gataquadrada** [comment]
Sim e sim e não tem erros (referente ao seu plugin ou CIELO) no log do meu PHP. E nem no da loja.

Por dúvidas, eu limpei os logs do PHP e apaguei o error.log da loja e tentei pagar com o plugin. Nada. error.log vazio.

A efeito de comparação, um plugin do Pagseguro que eu tenho apresenta tanto o log dele quanto registros no log do meu PHP.
Então não parece ser a minha configuração.

**Comment by vanderson139** [comment]
experimente instalar a versão mais recente, de preferência baixe aqui do github

**Comment by Gataquadrada** [comment]
É a que estou utilizando.

**Comment by adilsonmenezes** [comment]
Tente na pasta: system/logs

2016-01-08 12:03 GMT-02:00 Raphael Barreto notifications@github.com:

**Comment by Gataquadrada** [comment]
Essa pasta não existe.

**Comment by adilsonmenezes** [comment]
Para pagamento em Débito utilizando a bandeira Visa, apresenta seguinte
mensagem de erro:

ObrigatÃ³rio o envio dos campos CAVV e XID

Paras as outras formas de pagamento (bandeira Visa) está tudo funcionando!

Att.

2016-01-08 12:07 GMT-02:00 Raphael Barreto notifications@github.com:

**Comment by Gataquadrada** [comment]
Aqui continua sem funcionar. 
E, pior, sem retornar erros.

**Comment by adilsonmenezes** [comment]
Procura o erro através do comando die(var_dump($qualquercoisa)); nos
arquivos do módulo
Depois procurar via console do firebug o valor "impresso"; no momento que a
aplicação é interrompida pelo comando acima;

Lembrando de subtituir $qualquercoisa pela variavel/propriedade que você
quer verificar!

Eu tive um erro desse quando o numero do cartão era enviado para validação
com espaços. Na versão atual este erro foi corrigido.

2016-01-08 15:01 GMT-02:00 Raphael Barreto notifications@github.com:

**Comment by adilsonmenezes** [comment]
Para o pagamento com a Bandeira ELO, quando colocado o nr de teste
fornecido pela Cielo (6362970000457013) no campo Nº do Cartão, o mesmo não
é "formatado" como nas outras bandeiras e ao tentar realizar o pagamento
não ocorre nada (o botão não tenta realizar o processamento), como se o
valor do campo estive errado e não passou pela consistência do referido
campo.

Para o pagamento utilizando a Bandeira Discover, a mensagem ao tentar
utilizar o botão de Efetuar o Pagamento é: O XML informado não é válido

2016-01-08 15:01 GMT-02:00 Raphael Barreto notifications@github.com:

**Comment by Gataquadrada** [comment]
@adilsonmenezes Não sei se eu que não estou compreendendo suas respostas. Mas, ao que me parece, elas não fazem sentido e não estão relacionadas ao meu problema.

## 

Ademais, eu costumo dizer que quem sabe faz ao vivo.

Então, @vanderson139 , resolvi abrir o seu código para averiguar e vi que você chama a biblioteca da CIELO utilizando `$this->load->library('cielo')`.

O Opencart 2 não utiliza isso. Pois as bibliotecas dele são carregadas automaticamente.
Mas, isso também não significa que não é possível carregar uma biblioteca externa. Para tal, basta trocar qualquer referência do load acima por um simples `load('cielo')`.

**Comment by vanderson139** [comment]
@FineRapha adicionei uma verificação antes da chamada do método para manter a compatibilidade. vlw

**Comment by Gataquadrada** [comment]
Disponha.

**Comment by vanderson139** [comment]
@adilsonmenezes adicionei a validação para cartões ELO.

Não recomendo usar débito pela cielo, é um lixo, não consegui passar nenhum até o momento. A redecard, por exemplo, só garante transações no crédito.

**Comment by Gataquadrada** [comment]
@vanderson139 Já eu não tenho problemas com débito na CIELO, em uma loja que desenvolvi ano passado.

Só dá problema mesmo quando o sistema deles cai (o que é meio raro).

Só que, claro, se o desenvolvedor setar o script pra receber tudo automaticamente e processar sem a supervisão do Administrador da loja, VAI dar problema.
Porque, volta e meia, eles mandam notificações fora de ordem.
Mas basta apenas setar o sistema para buscar o status "manualmente".

**Comment by adilsonmenezes** [comment]
Boa tarde.

Raphael, para mim a função de débito sempre dá a mesma mensagem de erro:

Obrigatório o envio dos campos CAVV e XID

Pelo que li a respeito, a aplicação deveria neste momento ser redirecionado
para a operadora do cartão onde seria gerado os dois campos acima
mencionados, mediante confirmação de senha/chave pessoal. E então, depois
redirecionado pela URL que foi passado por XML (url-retorno), e somente
depois processado. Para mim não esta ocorrendo esse processo, talvez por
configuração e/ou problema no módulo.

Segue abaixo o xml que esta sendo gerado pela aplicação, antes de ser
processado, e capturada via interrupção do código php:

object(SimpleXMLElement)#74 (12) {
  ["@attributes"]=>
  array(2) {
    ["id"]=>
    string(1) "1"
    ["versao"]=>
    string(5) "1.4.0"
  }
  ["dados-ec"]=>
  object(SimpleXMLElement)#79 (2) {
    ["numero"]=>
    string(10) "1006993069"
    ["chave"]=>
    string(64) "25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3"
  }
  ["dados-portador"]=>
  object(SimpleXMLElement)#78 (5) {
    ["numero"]=>
    string(16) "4012001037141112"
    ["validade"]=>
    string(6) "201805"
    ["indicador"]=>
    string(1) "1"
    ["codigo-seguranca"]=>
    string(3) "123"
    ["token"]=>
    object(SimpleXMLElement)#81 (0) {
    }
  }
  ["dados-pedido"]=>
  object(SimpleXMLElement)#77 (7) {
    ["numero"]=>
    string(3) "373"
    ["valor"]=>
    string(5) "26800"
    ["moeda"]=>
    string(3) "986"
    ["data-hora"]=>
    string(19) "2016-01-11T18:37:47"
    ["descricao"]=>
    string(44) "Compra na xxxx"
    ["idioma"]=>
    string(2) "PT"
    ["soft-descriptor"]=>
    string(13) "Loja xxxx"
  }
  ["forma-pagamento"]=>
  object(SimpleXMLElement)#76 (3) {
    ["bandeira"]=>
    string(4) "visa"
    ["produto"]=>
    string(1) "A"
    ["parcelas"]=>
    string(1) "1"
  }
  ["url-retorno"]=>
  string(64) "http://www.xxxx.com.br/index.php?route=payment/cielo/callback"
  ["autorizar"]=>
  string(1) "3"
  ["capturar"]=>
  string(4) "true"
  ["campo-livre"]=>
  object(SimpleXMLElement)#75 (0) {
  }
  ["bin"]=>
  string(6) "401200"
  ["gerar-token"]=>
  string(5) "false"
  ["avs"]=>
  object(SimpleXMLElement)#80 (0) {
  }
}

Abraços.

Adilson

Em 8 de janeiro de 2016 17:56, Raphael Barreto notifications@github.com
escreveu:

**Comment by Gataquadrada** [comment]
@adilsonmenezes Isso acontece porque você está usando a modalidade Buy Page Loja com um código de loja e token da modalidade Buy Page Cielo.

**Comment by Gataquadrada** [comment]
Eu vou fechar o assunto porque ele desvirtuou e eu já dei a solução pro criador do plugin.
