### ISSUE TITLE
Cartão Inválido

### ISSUE THREAD

**Issue by criarth** [vanderson139/opencart-cielo#13]
Olá Vanderson tudo bem?

Instalei a nova versão do módulo (Cielo Webservice Transparente + OCMOD v1.1.9) no OpenCart 2.0.3.1, mas ao finalizar a compra recebo a mensagem de cartão inválido. Então instalei uma versão anterior (1.1.7) e recebo outra mensagem:

O XML informado não é valido: - string value 'Visï¿½o Gospel' does not match pattern for softDescriptorType in namespace http://ecommerce.cbmp.com.br: ''

Qual o procedimento para resolver esses problemas?

Desde já agradeço e um Feliz Ano Novo!

**Comment by vanderson139** [comment]
Olá Willian, tudo bem e aí?

Fiz várias alterações nessa última versão (v1.2.0). Também tive problemas parecidos com os que você descreveu e corrigi. Instale essa versão e me avise se está ok.

Abraço,
Feliz ano novo!

**Comment by criarth** [comment]
Olá Vanderson,

muito obrigado em responder!

Fiz a instalação com a nova versão (1.2.1) e ao finalizar a compra (modo teste), recebo a seguinte mensagem: O XML informado não é válido.

No log de erros do Opencart aparece estes avisos:
- PHP Notice:  Undefined index: address_id in /home/colheita/public_html/visaogospelstore.com.br/catalog/controller/payment/cielo.php on line 248
- PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br/>Error No: 1064<br/>SELECT iso_code_2 FROM oc_country WHERE country_id =  in /home/colheita/public_html/visaogospelstore.com.br/system/library/db/mysqli.php on line 41
- PHP Notice:  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1<br/>Error No: 1064<br/>SELECT code FROM oc_zone WHERE zone_id =  in /home/colheita/public_html/visaogospelstore.com.br/system/library/db/mysqli.php on line 41
- PHP Notice:  Undefined index: firstname in /home/colheita/public_html/visaogospelstore.com.br/catalog/controller/payment/cielo.php on line 276
- PHP Notice:  Undefined index: lastname in /home/colheita/public_html/visaogospelstore.com.br/catalog/controller/payment/cielo.php on line 277
- PHP Notice:  Undefined index: email in /home/colheita/public_html/visaogospelstore.com.br/catalog/controller/payment/cielo.php on line 282
- PHP Notice:  Undefined index: telephone in /home/colheita/public_html/visaogospelstore.com.br/catalog/controller/payment/cielo.php on line 288

Alguma dica de como resolver? Não sou programador, iniciei um curso de PHP, mas ainda estou só "engatinhando". rsrsrsrs

**Comment by criarth** [comment]
Olá Vanderson,

instalei a versão 1.2.1 em uma instalação do Opencart 2.1 e na finalização (modo de teste) nada acontece.

No log de erros está assim:

PHP Notice:  A non well formed numeric value encountered in /home/u404471143/public_html/catalog/controller/payment/cielo.php on line 491

**Comment by vanderson139** [comment]
@criarth corrigido na versão 1.2.2

**Comment by criarth** [comment]
@vanderson139, instalei a nova versão em duas instalações 2.0.3.1 e 2.1.0.1 e o resultado segue abaixo:

Opencart 2.0.3.1 -> http://snag.gy/2tZdp.jpg - sem log de erros.
Opencart 2.1.0.1 -> Nada acontece e sem log de erros

**Comment by adilsonmenezes** [comment]
Bom dia.

Para pagamento utilizando cartão de débito retorna a seguinte mensagem:

Obrigatório o envio dos campos CAVV e XID

Pelo o que eu vi em sites da internet o xml gerado deveria possuir os nodes:

<ExternalAuthentication>
  <Cavv>XXXXXX</Cavv>
  <Xid>XXXXXX</Xid>
  <Eci>XXXXXX</Eci>
</ExternalAuthentication>

Estes nodes estão implentados no seu módulo? E tem algum problema na
configuração do mesmo! Ou realmente é um item a ser incluso?

Att.

Em 8 de janeiro de 2016 18:34, Willian de Souza notifications@github.com
escreveu:

**Comment by adilsonmenezes** [comment]
Foi me falado pelo Raphael Barreto: "Isso acontece porque você está usando a modalidade Buy Page Loja com um código de loja e token da modalidade Buy Page Cielo."

Isso quer dizer que eu devo utilizar um cartão de débito real para o teste? Pois nenhum dos numeros disponibilizados deram resultado diferente do acima citado!

**Comment by vanderson139** [comment]
@adilsonmenezes isso quer dizer que seu contrato não permite uso de Webservice

**Comment by vanderson139** [comment]
@criarth estou corrigindo a codificação de caracteres, acredito que o problema seja no nome da loja, como é utf8 e a cielo só aceita ISO, está estourando o limite de caracteres para esse campo

**Comment by vanderson139** [comment]
@criarth resolvido, a cielo não aceita acentos no campo soft-description (nome da loja), a nova versão do módulo remove os acentos

**Comment by criarth** [comment]
@vanderson139, mais uma vez obrigado por sua atenção!

A mensagem de XML inválido não aparece mais, porém nada acontece, nenhum erro é reportado. Será que pode ser algum problema no Opencart? O módulo está em modo de teste e utilizando os dados de cartão de teste.

**Comment by criarth** [comment]
@vanderson139, outros módulos de pagamento estão funcionando corretamente (PayPal e PagSeguro), só estou com problemas com a Cielo.

**Comment by vanderson139** [comment]
@criarth falha minha, baixe o arquivo atualizado

**Comment by criarth** [comment]
@vanderson139, no arquivo cielo.log está assim:

# --- Obs: Copiei apenas referente ao último teste que fiz ---

<?xml version="1.0" encoding="ISO-8859-1"?>
<requisicao-transacao id="1" versao="1.4.0"><dados-ec><numero>1006993069</numero><chave>25fbb99741c739dd84d7b06ec78c9bac718838630f30b112d033ce2e621b34f3</chave></dados-ec><dados-portador><numero>4073020000000002</numero><validade>201812</validade><indicador>1</indicador><codigo-seguranca>123</codigo-seguranca><nome-portador>Willian de Souza</nome-portador><token/></dados-portador><dados-pedido><numero>89</numero><valor>100</valor><moeda>986</moeda><data-hora>2016-01-13T14:05:42</data-hora><descricao>Compra na loja Visão Gospel Store</descricao><idioma>PT</idioma><soft-descriptor>VISAO GOSPEL</soft-descriptor></dados-pedido><forma-pagamento><bandeira>visa</bandeira><produto>1</produto><parcelas>1</parcelas></forma-pagamento><url-retorno>https://visaogospelstore.com.br/index.php?route=payment/cielo/callback</url-retorno><autorizar>3</autorizar><capturar>true</capturar><campo-livre/><bin>407302</bin><gerar-token>false</gerar-token><avs><![CDATA[<dados-avs><endereco>Alameda Nilo Tavares</endereco><complemento/><numero/><bairro>Fazendinha</bairro><cep>25955270</cep></dados-avs>]]></avs></requisicao-transacao>

# 

<?xml version="1.0" encoding="ISO-8859-1"?>
<transacao versao="1.4.0" id="1" xmlns="http://ecommerce.cbmp.com.br">
  <tid>100699306900050E266A</tid>
  <pan>V6nVBGmf2fNY6FbOiqVZvlUq6J6aSnqdPulVI6lK4PU=</pan>
  <dados-pedido>
    <numero>89</numero>
    <valor>100</valor>
    <moeda>986</moeda>
    <data-hora>2016-01-13T12:05:44.286-02:00</data-hora>
    <descricao>Compra na loja Visï¿½o Gospel Store</descricao>
    <idioma>PT</idioma>
    <taxa-embarque>0</taxa-embarque>
  </dados-pedido>
  <forma-pagamento>
    <bandeira>visa</bandeira>
    <produto>1</produto>
    <parcelas>1</parcelas>
  </forma-pagamento>
  <status>6</status>
  <autenticacao>
    <codigo>6</codigo>
    <mensagem>Transacao sem autenticacao</mensagem>
    <data-hora>2016-01-13T12:05:44.309-02:00</data-hora>
    <valor>100</valor>
    <eci>7</eci>
  </autenticacao>
  <autorizacao>
    <codigo>6</codigo>
    <mensagem>Transação autorizada</mensagem>
    <data-hora>2016-01-13T12:05:44.313-02:00</data-hora>
    <valor>100</valor>
    <lr>00</lr>
    <arp>123456</arp>
    <nsu>300838</nsu>
  </autorizacao>
  <captura>
    <codigo>6</codigo>
    <mensagem>Transacao capturada com sucesso</mensagem>
    <data-hora>2016-01-13T12:05:44.340-02:00</data-hora>
    <valor>100</valor>
  </captura>
</transacao>

**Comment by criarth** [comment]
@vanderson139, resolvi enviar o arquivo completo.
[cielo.zip](https://github.com/vanderson139/opencart-cielo/files/89146/cielo.zip)

**Comment by criarth** [comment]
Olá @vanderson139 muito obrigado, funcionou perfeitamente em modo de teste. Agora vou aguardar os testes da Cielo e fecho esse tópico como resolvido. Acredito que não haverá nenhum problema.

Parabéns pela sua iniciativa e pelo suporte, mesmo sendo o módulo distribuído de forma gratuita.

Desejo muito sucesso em seus projetos e carreira profissional.

Att,

Willian de Souza

**Comment by vanderson139** [comment]
Obrigado @criarth sucesso para você também

**Comment by achoaki** [comment]
Boa Tarde Vanderson, tudo bom? Baixei seu modulo e estou testando no opencar 2.1.0.1, faço todos os passos para finalizar o pedido, coloco o numero de cartão e tudo, quando vou clicar no botão Efetuar pagamento, fica parado nessa tela. sabe o que pode ser? Obrigado
