### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by flaviovico** [vanderson139/opencart-cielo#14]
Inspecionando o elemento ao Clicar quem "Efetuar o pagamento" estou com o seguinte erro, e não segue para a pagina de sucesso, não faz nada

<b>Fatal error</b>: Class 'Tritoq\Payment\Cielo\Loja' not found in <b>/home/myloja/public_html/catalog
/controller/payment/cielo.php</b> on line <b>178</b><br />

**Comment by vanderson139** [comment]
Acredito que seja um problema com o autoloader padrão do Opencart, o qual só inclui pastas com nomes em letra minúscula

**Comment by flaviovico** [comment]
vanderson139 muito obrigado
