### ISSUE TITLE
Problema botão efetuar pagamento

### ISSUE THREAD

**Issue by rafaelbassora** [vanderson139/opencart-cielo#15]
Após testes o módulo não instala nesta versão.

**Comment by rafaelbassora** [comment]
o botão fica sem ação, modifiquei o título pois a anta aqui rs, tinha subido os arquivos no diretório errado.

**Comment by rafaelbassora** [comment]
Tentei mudar  no arquivo system/library/Tritoq/Payment/Cielo/Requisicao.php, porém sem sucesso.

**Comment by rafaelbassora** [comment]
Fatal error: Class 'Tritoq\Payment\Cielo\Loja' not found in /home/****/public_html/catalog
/controller/payment/cielo.php on line 178

**Comment by vanderson139** [comment]
#14
