### ISSUE TITLE
Erro no Requisicao.php

### ISSUE THREAD

**Issue by athosfidalgo** [vanderson139/opencart-cielo#16]
Estou recebendo este erro:
 PHP Warning:  SimpleXMLElement::asXML(): output conversion failed due to conv error, bytes 0xD3 0x54 0x49 0x43 in /system/library/Tritoq/Payment/Cielo/Requisicao.php on line 253

Aí quando clico em pagar, ele carrega e volta.
Alguém tem idéia do que seja isso?

**Comment by joelburigo** [comment]
Conseguiu resolver ?

**Comment by athosfidalgo** [comment]
No final nas contas comprei um módulo de webservice. Mas obrigado ;) 
Em 13 de jun de 2016 23:52, Joel Martins notifications@github.com escreveu:Conseguiu resolver ?
