### ISSUE TITLE
Cartão Débito

### ISSUE THREAD

**Issue by marcelloinfoweb** [vanderson139/opencart-cielo#19]
Retorno do status para pagamento no débito está sendo registrado na loja sempre como "Não autorizada" e não atualiza quando é capturado no site da Cielo, sendo assim, tendo que alterar manualmente na loja mesmo quando o status final no site da Cielo esteja como "Capturado".

Onde posso alterar para funcionar/sincronizar com o status real?

**Comment by vanderson139** [comment]
O processo de autorização não estava sendo executado no débito. Corrigido na última atualização
