### ISSUE TITLE
Falha no pagamento!

### ISSUE THREAD

**Issue by mathidios** [vanderson139/opencart-cielo#2]
Olá, @vanderson139, realizei a instalação e a compra NÃO em modo teste pela cielo de um produto de R$1,00 que foi cobrado em meu cartão e retorna essa mensagem:

Falha no pagamento!
Houve um problema ao processar o seu pagamento, por isso, seu pedido não foi concluído.
Possíveis causas:
•Não a crédito suficiente.
•Falha na verificação.
Você pode tentar novamente utilizando outra forma de pagamento.
Se o problema persistir, entre em contato conosco e nos informe os detalhes do seu pedido.

O que posso fazer?
###### 

Olá, @mathidios, o valor foi debitado do seu cartão? Verifique as mensagens da transação na tabela 'oc_order_cielo'
###### 

@vanderson139 a "autorizacao_mensagem" no BD esta como "Transacaoo autorizada". No extrato do cartão de credito apresenta a cobrança. O único problema é esta mensagem no final falando de falha.

**Comment by vanderson139** [comment]
@mathidios esse erro realmente acontecia e foi corrigido na versão mais recente pq não estava validando corretamente o status da transação ao final da operação.

Eu adicionei essa validação na linha 622 do arquivo catalog/controller/payment/cielo.php

``` php
if(!in_array($transacao->getStatus(), array(
    \Tritoq\Payment\Cielo\Transacao::STATUS_ERRO,
    \Tritoq\Payment\Cielo\Transacao::STATUS_CRIADA,
    \Tritoq\Payment\Cielo\Transacao::STATUS_NAO_AUTENTICADA,
    \Tritoq\Payment\Cielo\Transacao::STATUS_NAO_AUTORIZADA
))) {
    return $this->response->redirect($this->url->link('checkout/success'));
}
```

A versão que você instalou possui essas linhas? Se não, baixe a versão mais recente.

**Comment by mathidios** [comment]
@vanderson139 a minha versão possui este código sim e mesmo assim ainda apresenta o erro.

**Comment by vanderson139** [comment]
vc ta usando autenticação na transação, ou autorização direta? Pode me informar o código do status da transação?

**Comment by mathidios** [comment]
estou usando a opção "Autorizar somente se for autenticada", Capitura automatica = sim

**Comment by vanderson139** [comment]
eu alterei a validação do status da transação, mas não testei ainda. Se quiser fazer um teste, baixe aqui do github a versão alterada.

**Comment by mathidios** [comment]
Infelizmente continua apresentando a mesma tela.

**Comment by mathidios** [comment]
Existe alguma solução?

**Comment by igorjapo** [comment]
Desculpa Abri outro tópico com mesma duvida, teria alguma solução?

**Comment by vanderson139** [comment]
Estou com duas lojas funcionando, mas estou usando autorização direta, porque foi o processo homologado. Vocês homologaram a opção "Autorizar somente se autenticada" ?

Tem que verificar se está habilitada esta opção junto à Cielo.

**Comment by criarth** [comment]
Olá Vanderson,
quando utilizo o tema padrão do Opencart, funciona legal, porém quando utilizo o template que comprei (Journal), na Cielo registra a compra e a captura, mas o site retorna uma mensagem de falha e não gera nenhum log de erro. Quando vc cobra para fazer funcionar com esse template?
