### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by igorjapo** [vanderson139/opencart-cielo#3]
Por favor preciso de ajuda. sempre retorna esse erro
## 

FALHA NO PAGAMENTO!

Houve um problema ao processar o seu pagamento, por isso, seu pedido não foi concluído.

Possíveis causas:

Não a crédito suficiente.
Falha na verificação.
Você pode tentar novamente utilizando outra forma de pagamento.

Se o problema persistir, entre em contato conosco e nos informe os detalhes do seu pedido.

**Comment by vanderson139** [comment]
Também estou com o mesmo problema, na maioria das vezes quando passo um cartão Master do Itaú no débito. Ainda sem solução
