### ISSUE TITLE
Call to undefined method Loader::library() cielo.php on line 154

### ISSUE THREAD

**Issue by leopucci-zz** [vanderson139/opencart-cielo#4]
Boa noite, 

estou tendo problemas com este erro na ultima versao do magento. 
Eu já fiz downgrade para a Versão 2.0.3.1, estou postando só pra voce ter noção de alguma modificação que é necessaria para a proxima versao
:)

 public function processar() {

```
    $this->load->library('cielo');
```

/index.php?route=payment/cielo&token=
 /opt/pucci/html/openc/admin/controller/payment/cielo.php on line 613,

**Comment by vanderson139** [comment]
Obrigado @leopucci já fiz essa alteração
