### ISSUE TITLE
Homologação:  mensagem do status na página de retorno  

### ISSUE THREAD

**Issue by leopucci-zz** [vanderson139/opencart-cielo#5]
Fiz a homologação usando este modulo e o retorno da cielo foi o seguinte:

Favor alterar a mensagem do status na página de retorno, uma vez que não houve falha alguma; no caso abaixo a transação processou corretamente porém foi Negada pelo banco emissor do cartão. É necessário que o cliente tenha ciência do retorno bancário, ou seja, se a transação foi “Autorizada” ou “Não Autorizada”. Apenas a tag <mensagem> do nó <autorizacao> é suficiente.

Ressaltamos que os campos para digitação do número do cartão e código de segurança devem estar limitados à digitação apenas de números (19 e 4, respectivamente). Favor verificar.

**Comment by leopucci-zz** [comment]
Fiz uma implementação da mensagem de status alterando o código da callback e o retorno para checkout/failure com a tag mensagem do no autorizacao (autorizacao_mensagem). 
Entretando tive que alterar o arquivo core checkout/failure para mostrar esta mensagem na tela. 
Nao gostaria de subir com alteração em core, mas sim converter minha modificação para OCMOD. 

No f.d.s tendo um tempinho ja faço e subo
![image](https://cloud.githubusercontent.com/assets/5239210/10738739/efc81cfa-7bff-11e5-8251-7d5763f48ef5.png)

**Comment by lguilhermecardoso** [comment]
tbm estou com o mesmo problema.

**Comment by leopucci-zz** [comment]
@bijow Fim de ano ta corrido pra mim, desculpe ainda nao subi esta modificação para o github, nem mudei o codigo para ocmod

**Comment by lguilhermecardoso** [comment]
Aonde vc mudou no codigo so falta isso pra dar tudo certo na minha loja, o modo de autorização qual vc usa?

**Comment by lguilhermecardoso** [comment]
no caso meu eu arrumei fazendo uma verificação dos códigos de Retorno da Cielo de acordo com o manual de desenvolvedor deles.

**Comment by leopucci-zz** [comment]
Desculpe, nao tive tempo de pegar o codigo em casa.
Que bom que deu certo!
Em 10/12/2015 08:10, "bijow" notifications@github.com escreveu:
