### ISSUE TITLE
Opencart 1.5.6 posso fazer ele se tornar compatível?

### ISSUE THREAD

**Issue by LucasHiago** [vanderson139/opencart-cielo#9]

**Comment by vanderson139** [comment]
Pode sim, me mande um pull-request quando terminar

**Comment by LucasHiago** [comment]
Olá vanderson139, eu consegui fazer a cielo carregar algumas coisas na versão 1.5.6 corrigindo os erros que apareciam.

Eu agora estou tentando chamar o método load, porém esse bendito sempre me vem com erro diferente. Meu último erro com ele é que o método não está definido. Aí eu defino ele, só que continua com o seguinte erro:

Fatal error: Call to undefined method Loader::controller() in C:\xampp\htdocs\centerloja\control\set\admin\controller\common\column_left.php on line 5

é alguma coisa que a versão 1.5.6 não tem? 
e tem na versão 2.x+

**Comment by LucasHiago** [comment]
Segue a linha de comando do endereço: C:\xampp\htdocs\centerloja\control\set\admin\controller\payment\cielo.php

263-271

$this->template = 'payment/cielo_list.tpl';
    $this->children = array(
        'common/header',
        'common/footer',
        'common/column_left'

```
);

$this->response->setOutput($this->render());
```

**Comment by LucasHiago** [comment]
![image](https://cloud.githubusercontent.com/assets/15170878/11005686/6b22a7c2-84a6-11e5-872d-8e7fc2c6cb58.png)
Garrei nisso aqui...

**Comment by LucasHiago** [comment]
Preciso chamar a classe Column_left, más toda vez que uso o método load, da o erro falando que o método loader é indefinido. kkkk qual IDE você usa para programar? ou está no sublime também?

**Comment by LucasHiago** [comment]
Já sei por que está assim... eu não chamei o método e muito menos a classe column_left eu só taquei uma view nela e esperei por um milagre =X. 
Sou uma vergonha para o meu clã.
